### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:unpack-dependencies 

### ISSUE THREAD

**Issue by chrisbangun** [salesforce/Argus#188]
Hey guys, I am trying to install Argus in my machine. I've installed all (I hope I did not miss any) the dependencies mentioned in https://github.com/SalesforceEng/Argus/wiki/Getting%20Started. But when I try running mvn test, I got this error:
INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Argus ............................................. SUCCESS [0.555s]
[INFO] ArgusCore ......................................... SUCCESS [4:03.576s]
[INFO] ArgusWebServices .................................. FAILURE [0.062s]
[INFO] ArgusClient ....................................... SKIPPED
[INFO] ArgusSDK .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4:04.305s
[INFO] Finished at: Wed Sep 28 18:06:46 WIB 2016
[INFO] Final Memory: 64M/929M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:unpack-dependencies (unpack-shared-resources) on project argus-webservices: Artifact has not been packaged yet. When used on reactor artifact, unpack should be executed after packaging: see MDEP-98. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :argus-webservices

Any advice? Thanks

**Comment by saaja-sfdc** [comment]
Hi @chrisbangun ,  can you instead try the steps outlined in https://github.com/SalesforceEng/Argus#building-argus and see if you run into the same issue.  I think that you may not have performed the pre-build step that installs the resource filters for the sub-modules (https://github.com/SalesforceEng/Argus#installing-the-resource-filters) as it's not explicitly listed in the Getting Started link you mentioned.

**Comment by chrisbangun** [comment]
halo @saaja-sfdc thanks for your prompt feedback. I tried the steps outlined in [https://github.com/SalesforceEng/Argus#building-argus](here), however I still get the same issue. I am afraid that I haven't really grasp about what I need to do/modifying the `argus-build.properties`.

**Comment by saaja-sfdc** [comment]
Hi @chrisbangun, can you please try the following steps?  I just verified this flow.  If it works for you, I'll update the wiki to reflect it.

% git clone https://github.com/SalesforceEng/Argus.git
% cd Argus
% git checkout -b develop origin/develop
% mvn -DskipTests=true --non-recursive package
% mvn test

This will run the unit tests and after about 5-6 minutes, you should see:
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Argus .............................................. SUCCESS [  0.798 s]
[INFO] ArgusCore .......................................... SUCCESS [04:22 min]
[INFO] ArgusWebServices ................................... SUCCESS [  2.633 s]
[INFO] ArgusClient ........................................ SUCCESS [ 33.993 s]
[INFO] ArgusSDK ........................................... SUCCESS [  3.289 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:03 min
[INFO] Finished at: 2016-09-30T11:46:49-07:00
[INFO] Final Memory: 57M/799M
[INFO] ------------------------------------------------------------------------

You should not have to do anything with argus-build.properties unless you want to run integration tests.  Once you get unit tests to pass I can help you run the integration tests.

**Comment by saaja-sfdc** [comment]
@chrisbangun , just following up here.  Did this resolve your problem?

**Comment by chrisbangun** [comment]
hi @saaja-sfdc , sorry for my late reply. It did not resolve the issue that I have. I've followed your instructions, but unfortunately I got the following error:
[ERROR] Failed to execute goal on project argus-core: Could not resolve dependencies for project com.salesforce.argus:argus-core:jar:2.2.0-SNAPSHOT: The following artifacts could not be resolved: com.salesforce.argus:argus:zip:resources:2.2.0-SNAPSHOT, com.salesforce.argus:argus:zip:test-resources:2.2.0-SNAPSHOT: Could not find artifact com.salesforce.argus:argus:zip:resources:2.2.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :argus-core

**Comment by saaja-sfdc** [comment]
@salesforce/argus

**Comment by saaja-sfdc** [comment]
The following should work.  Make sure that you delete your ~/.m2/repository/com/salesforce/argus dir first if needed.

% git clone https://github.com/SalesforceEng/Argus.git
% mvn -DskipTests=true --non-recursive package -install
% mvn test
