### ISSUE TITLE
UI: Discovery lookup pannel crash if no result fetched from discovery service 

### ISSUE THREAD

**Issue by aertoria** [salesforce/Argus#209]
in a rare case UI will crash:  Discovery Discovery lookup pannel crash if no result fetched from discovery service.

Example:

Chrome/Firefox/Safari
Discovery lookup, scope text box:   core.TYO
result: 
Error msg:  $scope.searchMetrics/<@https://argus-ui.data.sfdc.net/argus/js/controllers/viewMetrics.js:92:21

**Comment by saaja-sfdc** [comment]
@cnardi-dev

**Comment by saaja-sfdc** [comment]
@salesforce/argus

**Comment by aertoria** [comment]
This problem has be fixed by recent release.
