### ISSUE TITLE
Argus available as deployable docker images?

### ISSUE THREAD

**Issue by rmelick** [salesforce/Argus#302]
I would like to be able to deploy argus as a relatively simple docker image (similar to the opentsdb image: https://hub.docker.com/r/petergrace/opentsdb-docker/).  I'm happy to create the images somewhere in this repository or a related one if other thinks it would be a good idea.  Any thoughts or suggestions?

**Comment by saaja-sfdc** [comment]
@rmelick that would be awesome.  It's on our long list of things to do.  I think the best thing is to create a fork or separate repo that we can review and if it make sense merge in.  If in the future it's moved into the Salesforce org, there's some logistical stuff that would need to happen.  We can address that when the time comes.  Please reach out to us if you need any info, help, etc...
