### ISSUE TITLE
Update references to salesforceEng project

### ISSUE THREAD

**Issue by rmelick** [salesforce/Argus#314]
I noticed the travis CI button and some of the wiki links are still referring to the old project name (salesforceEng/Argus) before the migration (#108).

I couldn't figure out if the Coverity job also needed to be modified.

**Comment by saaja-sfdc** [comment]
Hi @rmelick, /develop is our working branch.  Can you please rebase and submit your PR against that branch so that we can merge those changes.

**Comment by saaja-sfdc** [comment]
Thanks for this contribution!
