### ISSUE TITLE
parent pom is not published to maven central

### ISSUE THREAD

**Issue by rmelick** [salesforce/Argus#316]
The argus parent pom is not published to maven central (http://search.maven.org/#search%7Cga%7C1%7Cargus).  This makes it impossible for maven to resolve dependencies on the subprojects correctly.

I created a test project (https://github.com/rmelick/argusclient) that shows the following failure if you build with `mvn package -s settings.xml -U`

```
[ERROR] Failed to execute goal on project argustest: Could not resolve dependencies for project net.rmelick.maven:argustest:jar:1.0-SNAPSHOT: Failed to collect dependencies at com.salesforce.argus:argus-client:jar:2.1.1: Failed to read artifact descriptor for com.salesforce.argus:argus-client:jar:2.1.1: Could not find artifact com.salesforce.argus:argus:pom:2.1.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

```

**Comment by saaja-sfdc** [comment]
I've pushed all artifacts including the parent pom to nexus and will do so for future releases as well.
https://oss.sonatype.org/#nexus-search;quick~argus.

They should show up in maven central in an hour or so.

**Comment by saaja-sfdc** [comment]
http://search.maven.org/#search%7Cga%7C1%7Cargus
