### ISSUE TITLE
Update default branch to `develop` via GitHub admin interface

### ISSUE THREAD

**Issue by mbrukman** [salesforce/Argus#318]
Per issue #314, the main branch for the repository is `develop`, not `master`.

Could an admin of the repo please [update the default branch](https://help.github.com/articles/setting-the-default-branch/) via GitHub settings?

> The default branch is considered the base branch in your repository, against which all pull requests and code commits are automatically made, unless you specify a different branch.
>
> Your default branch is named `master`. If you have admin rights over a repository on GitHub, you can change the default branch on the repository.

**Comment by saaja-sfdc** [comment]
Done.
