### ISSUE TITLE
Plans to upgrade to HBase 1.x?

### ISSUE THREAD

**Issue by mbrukman** [salesforce/Argus#319]
Per [`ArgusCore/pom.xml`](https://github.com/salesforce/Argus/blob/3e38a10cf6979b75481a07dc1a9e8b62f9904ee0/ArgusCore/pom.xml#L347-L349), it looks like Argus is currently using HBase 0.98:

> ```xml
> <groupId>org.apache.hbase</groupId>
> <artifactId>hbase-client</artifactId>
> <version>0.98.8-hadoop2</version>
> ```

Are there any plans for upgrading to HBase 1.x APIs?

**Comment by saaja-sfdc** [comment]
Hi Misha,  we are planning on upgrading as part of the roll out of the Phoenix TSDB engine.  We'll be working with the Phoenix team on that in H1.
