### ISSUE TITLE
Preferences for wiki updates?

### ISSUE THREAD

**Issue by rmelick** [salesforce/Argus#322]
Once the docker images are available (#302), I'll need to update the wiki to describe how to properly use them.  I was also thinking of enhancing a few other parts that confused me when I tried to get started deploying Argus.  Before I start, I have the following questions:

- How do wiki updates work?  Should I clone the wiki (https://github.com/salesforce/Argus.wiki.git) and create a new branch with my changes?
- I would like to add a few architecture diagrams to the wiki.  Is there a preferred diagram editor (hopefully also accessible on linux?).  I was thinking of https://www.draw.io/, Google Docs, or OpenOffice Draw.
- Is there general guidance about what goes in the README vs. what goes in the wiki?

**Comment by rmelick** [comment]
I attempted to push some wiki chages to a new branch, but they failed with the following error:

```
git push --set-upstream origin update-deployment
remote: Permission to salesforce/Argus.wiki.git denied to rmelick.
fatal: unable to access 'https://github.com/salesforce/Argus.wiki.git/': The requested URL returned error: 403
```
I have created a branch called update-deployment at https://github.com/rmelick/Argus.wiki.git with my changes:

It can also be seen here:
https://github.com/rmelick/Argus/wiki

**Comment by saaja-sfdc** [comment]
Yep, that is how we merge wiki changes. I'll pull your changes down, review and merge.

**Comment by saaja-sfdc** [comment]
We don't prescribe any particular drawing editor. Feel free to use what you prefer.  We try to keep the readme limited to a short description and the minimum info to get started and add the detailed info in the wiki.

**Comment by saaja-sfdc** [comment]
We don't prescribe any particular drawing editor. Feel free to use what you prefer.  We try to keep the readme limited to a short description and the minimum info to get started and add the detailed info in the wiki.
