### ISSUE TITLE
Runtime configuration of database connection 

### ISSUE THREAD

**Issue by rmelick** [salesforce/Argus#342]
I would like to be able to configure the database connection (at a minimum the user name and password) at runtime.  This would allow me to deploy my same built war to multiple environments (for example test and production).

It seems there are a few comments out there about how to do it for hibernate or through directy property setting in java (http://stackoverflow.com/questions/8324821/properties-reference-for-hibernate-in-persistence-xml and http://stackoverflow.com/questions/3935394/how-to-externalize-properties-from-jpas-persistence-xml).  How do you do it at salesforce?

**Comment by saaja-sfdc** [comment]
it's set in the argus-build.properties when we build the artifacts for production.  These properties act as a resource filter that ultimately updates persistence.xml in argus-core.  The property name is build.property.persistence.unit and should be updated with the content of the <provider/> element of your specific persistence unit engine.

**Comment by rmelick** [comment]
@saaja-sfdc , do you mind explaining how the build and deployment process for Argus works at Salesforce?  Requiring a separate build for each environment won't work well with creating Docker images, and it also won't match with how we were hoping to build and deploy at kiwigrid.  

Our plan was as follows:

- In the normal case, we would be deploying the publicly available argus artifacts from maven central or from the public docker images.  If we had a bugfix or feature that was not time critical, we would create a pull request against the develop branch in the public repo and wait for the new release.
- For super urgent hotfixes, we would fork the public repo and create a new branch based on our currently deployed release (e.x. 2.2).  We would make the patch there, and also create a pull request to the public develop branch.  While we waited for the new public release, we would run a local build of our fork, push the artifacts to our internal nexus, and deploy them.  Then, once the new public version was available, we would deploy it instead of our hotfixed version.

Obviously, this won't work if all the public builds are environment specific.  It seems like the persistence.xml is the maing thing preventing us from setting all the configuration at runtime instead of build time.  I think we could fix that by modifying the configurePersistence() method in SystemInitializer to allow setting properties on the jpaPersistModule.

Does it make sense to try and use the same argus build in multiple environments, or am I completely missing something?

**Comment by saaja-sfdc** [comment]
No you're not missing anything.  This is our goal as well.  The static binding of JPA at build time is an artifact from early Argus.  

👍
