### ISSUE TITLE
how to intall? The document give on wiki is not clear. 

### ISSUE THREAD

**Issue by davis1214** [salesforce/Argus#350]
how to intall? The document give on wiki is not clear.

**Comment by rmelick** [comment]
@davis1214 I have a pull request open to get some docker images built and some improvements to the wiki.  If you want to try that, take a look at the wiki:

https://github.com/rmelick/Argus/wiki/Building-and-Deploying

and the readme for the docker-compose setup:

https://github.com/rmelick/Argus/tree/docker-images/ArgusDocker

Basically, you need to do the following:
1) From the root project, run `mvn install`
2) Then, `cd ArgusDocker/simple`
3) Then, `docker-compose up`
