### ISSUE TITLE
PerfFilter throws NPE when filtering URL request of the root context without trailing '/'

### ISSUE THREAD

**Issue by saaja-sfdc** [salesforce/Argus#368]
https://github.com/salesforce/Argus/blob/f85e4a138d057a6fe0f4e44ab2f20c9fb09b694a/ArgusWebServices/src/main/java/com/salesforce/dva/argus/ws/filter/PerfFilter.java#L118

If the requested URL is the context root without any trailing '/', then the getPathInfo() returns null resulting in an NPE.

**Comment by rajsarkapally** [comment]
This is fixed.. So closing
