### ISSUE TITLE
transform purposed: deduct

### ISSUE THREAD

**Issue by aertoria** [salesforce/Argus#375]
hi @saaja-sfdc @rajsarkapally-sfdc 
Recently I'm needing this transform. Please let me know if it is already implemented. Otherwise I will write one and have it pr.

DEDUCT(M1, M2)   It returns M1 - M2 from time dimension. It remove all items from M1 whose keys are found in M2. This is the opposite of UNION. 

Note:  it is not MIN, MIN only align both Metric up by key, and do the value minus.

Usage:  DEDUCT(List<Metric>). 
Example: 
input:
M1 is     1L:10, 2L:10, 3L:20
M2 is     1L:10

output as DEDUCT(M1,M2)
M is        2L:10, 3L:20

**Comment by bsura** [comment]
What would be the behavior when the list size is greater than 3. For e.g.:

Input:
M1 = 1L:10, 2L:10, 3L:20
M2 = 1L:10
M3 = 2L:10

Output?

**Comment by aertoria** [comment]
Hi @bsura, good question. 

It will be likely
M1-M2-M3

Similar to M1- UNION(M2,M3)

**Comment by bsura** [comment]
@aertoria Are you still going to pursue this? If so, then please submit a PR with the implementation.

**Comment by aertoria** [comment]
Sure. It's already complete in dbcloud's instance. Will submit this pr this week
