### ISSUE TITLE
Discovery service returning duplicate result

### ISSUE THREAD

**Issue by aertoria** [salesforce/Argus#498]
Discovery service returning duplicate result

For example, there are two metrics:
`core.WAS.SP1.a`
`core.WAS.SP1.b`

when user type `core.was.*` the result is showing two record as below:
`core.WAS.SP1`
`core.WAS.SP1`
rather than just one.

As a result, the discovery window is easily fully occupied and become less useful.

**Comment by aertoria** [comment]
![argus](https://cloud.githubusercontent.com/assets/3536746/23874853/6d39c068-07f4-11e7-9d83-53f81e949afd.png)

**Comment by bsura** [comment]
This was tracked internally and has been fixed as part of this PR. 
https://github.com/salesforce/Argus/pull/483
