### ISSUE TITLE
Discovery Service fetch limit estimation

### ISSUE THREAD

**Issue by aertoria** [salesforce/Argus#504]
Discovery Service fetch limit estimation: currently is based on the assumption of minute resolution and multiplies with time range. This causing lots of query been overestimated and therefore failed to fetch.

To fix this, purposing, please first take a sample to determine the average resolution and then use it to decide the data volume that will be fetched.

Let me know if you need more details.

@saaja-sfdc @kgowdru

**Comment by bsura** [comment]
We could do that, but that would just increase the query latency. Also what would represent an accurate sample? If we end up choosing a sample containing granular data, then we would underestimate. It we end up choosing a sample containing coarse data, we would overestimate. 

In your case, if your data is less granular than 1 minute interval, then you could use downsampling (since the estimator also takes downsampling into the account).

**Comment by aertoria** [comment]
Thanks for replying.
1, it won't increase the latency if you do this async. Based on the natural of the task "estimate volume", it's non-essential to the query fetching task. If you do it async-ly, once you estimated volume turn out to be huge you can always cancel the query.

2, Yes sampling is not perfect. But it is better than no sample at all. In our day-to-day use it will fit in well will majority of our metrics.

3, downsampling first is a good technique, but based on the the business use case, some time it's not possible to do it and keep the result mathematically correct at the same time. 

There are lots volume estimation approach you can try, for example, have you guys thought about keep each sample gran into your discovery service hbase schema and store as value?

**Comment by rajsarkapally-sfdc** [comment]
How about taking the granularity from the TSDB down sample part of the metric expression? This will eliminate querying HBase for the granularity

for example, for the following expression, the granularity is 1 hour instead of 1 min?

-1h:argus.jvm:mem.heap.used{host=*}:sum:1h-sum

**Comment by aertoria** [comment]
@rajsarkapally-sfdc 

I agree, except for the cases below:

let's say `argus.jvm:mem.heap.used{host=*}:sum` original granularity is 1 datapoint per day.
in this case, even you downsample to `1h-sum`, it still stays at day resolution. I don't think TSDB's down-sample will fill 0 if no dps presented.

e.g.
`-4m:argus.jvm:mem.heap.used{host=*}:sum:1s-sum`

**Comment by rajsarkapally-sfdc** [comment]
When we know the granularity is 1 day per data point, how about using something like this

-2d:argus.jvm:mem.heap.used:sum:1d-avg

**Comment by aertoria** [comment]
I see. That's sound workable to me.

And I assume you guys will use the downsampler to adjust the estimation?

**Comment by bsura** [comment]
Didn't I just say the same thing above (confused face). Apologies if I was unclear. From my previous comment "(since the estimator also takes downsampling into the account)", yes we do take downsampling into account. If all this sounds reasonable then can we close this issue?

**Comment by aertoria** [comment]
@bsura sorry mis-read your comments. Thanks for informing. I will close it.
