### ISSUE TITLE
Bug: Downsample transform, the timestamp after downsample is not accurate

### ISSUE THREAD

**Issue by aertoria** [salesforce/Argus#514]
Bug: Downsample transform, the timestamp after downsample is not accurate

For example:
When time range is smaller than downsample resolution.

`-2d:REDUCED.SLA.db:ImpactedMin:avg`

`DOWNSAMPLE(-2d:REDUCED.SLA.db:ImpactedMin:avg,#99d-avg#)`

https://github.com/salesforce/Argus/blob/develop/ArgusCore/src/main/java/com/salesforce/dva/argus/service/metric/transform/DownsampleTransform.java

```
    /*
     * i.e.
     * on hour level, 01:01:30 => 01:00:00
     * on minute level, 01:01:30 => 01:01:00
     * on second level, 01:01:30 => 01:01:30
     */
    public static Long downsamplerTimestamp(Long millitimestamp, long windowSize) {
    	return millitimestamp-(millitimestamp%windowSize);
    }
```

**Comment by bsura** [comment]
We have made modifications to the DOWNSAMPLE transform that should fix this. We will close this story.

**Comment by aertoria** [comment]
Havn't been following this for long time. But I believe DBVA is waiting on this. Would you please attach a p.r. link here plz?

**Comment by bsura** [comment]
https://github.com/salesforce/Argus/pull/682
