### ISSUE TITLE
No way to change the case of a parameter place holder

### ISSUE THREAD

**Issue by rmichela** [salesforce/Argus#664]
I have a dashboard with an `<ag-text>` parameter for `datacenter`.
```xml
<ag-text type="text" name="datacenter" label="Datacenter" default="STAGE"></ag-text>
```
Some of my metrics have the `datacenter` variable in UPPERCASE, and some are in lowercase. Argus needs a way to adjust the case of text parameters used in binding expressions.

My hacky fix is to have a second `<ag-text>` parameter for `datacenter-lower-case`, but this is _very_ suboptimal.

**Comment by rajsarkapally** [comment]
We moved Argus Web to a new github repo.. This issue can be tracked at https://github.com/salesforce/ArgusWeb/issues/11
