### ISSUE TITLE
HBaseHistoryService and AsyncHbaseSchemaService need create hbase table manually?

### ISSUE THREAD

**Issue by sumpan** [salesforce/Argus#676]
hi , 
I setup Argus and use some default config properties for historyservice and schemaservice,
but I think this system is not working fine ,because I do not find that hbase tables in my hbase cluster .
so would you please tell me ,that tables should be created manually? and what's the table structure?

HBASE_TABLE("service.property.history.hbase.table", "history");
HBASE_METRICSCHEMA_TABLE("service.property.schema.hbase.metricschema.table", "metric-schema"),
HBASE_SCOPESCHEMA_TABLE("service.property.schema.hbase.scopeschema.table", "scope-schema");

**Comment by bsura** [comment]
This is what we use:

// You can ignore the compression and data block encoding if you like. 
create 'metric-schema', {NAME => 'f', BLOOMFILTER => 'ROW', VERSIONS => '1', COMPRESSION => 'SNAPPY', DATA_BLOCK_ENCODING => 'FAST_DIFF'}

// You can ignore the compression and data block encoding if you like. 
create 'scope-schema', {NAME => 'f', BLOOMFILTER => 'ROW', VERSIONS => '1', COMPRESSION => 'SNAPPY', DATA_BLOCK_ENCODING => 'FAST_DIFF'}

// We expire history records after 2 weeks. 
create 'history', {NAME => 'f', BLOOMFILTER => 'ROW', VERSIONS => '1', DATA_BLOCK_ENCODING => 'FAST_DIFF', COMPRESSION => 'SNAPPY', TTL => '1209600'}

**Comment by rajsarkapally** [comment]
@sumpan  we are closing this issue as we provided the answer.
