### ISSUE TITLE
Update auth page to be only about tokens

### ISSUE THREAD

**Issue by textractor** [salesforce/Argus#687]
[This wiki page](https://github.com/salesforce/Argus/wiki/Token-Based-Authentication#how-do-i-use-token-based-auth) talks about the transition to token-based authentication, but should be rewritten to reflect only tokens, and not refer to a transition.

**Comment by textractor** [comment]
@kgowdru This is the issue to track what I spoke to you about.

**Comment by kgowdru** [comment]
Its already updated to use token based auth.
