### ISSUE TITLE
Alerts are not evaluated until client is restarted

### ISSUE THREAD

**Issue by sgarg7** [salesforce/Argus#696]
I noticed that when I create a new alert or change an existing one, the new alerts don't run immediately or they are not updated (needed a restart of alert client). I know they are not updated because I see alerts being enqueued on the alertQueue with old definitions.

I can't understand exactly how the object refreshes are done, I'm guessing the QuartzSchedulingService and the DefaultDistributedSchedulingLockService have something to do with it.

Here are the service bindings and scheduling properties from the log on start.

	service.binding.alert : com.salesforce.dva.argus.service.alert.DefaultAlertService
	service.binding.auth : com.salesforce.dva.argus.service.auth.NoAuthService
	service.binding.cache : com.salesforce.dva.argus.service.cache.RedisCacheService
	service.binding.callback : com.salesforce.dva.argus.service.callback.DefaultCallbackService
	service.binding.history : com.salesforce.dva.argus.service.history.DefaultHistoryService
	service.binding.mail : com.salesforce.dva.argus.service.mail.DefaultMailService
	service.binding.mq : com.salesforce.dva.argus.service.mq.kafka.KafkaMessageService
	service.binding.scheduling : com.salesforce.dva.argus.service.schedule.QuartzSchedulingService
	service.binding.schema : com.salesforce.dva.argus.service.schema.ElasticSearchSchemaService
	service.binding.tsdb : com.salesforce.dva.argus.service.tsdb.SingletonTSDBService
	service.binding.warden : com.salesforce.dva.argus.service.warden.DefaultWardenService

	service.property.scheduling.jobsBlockSize : 2000
	service.property.scheduling.maxJobsPerScheduler : 4000
	service.property.scheduling.quartz.threadPool.threadCount : 10
	service.property.scheduling.schedulingRefeshInterval : 300000

I also wanted to understand - since the alert scheduling is done using the Kafka queue, how far in advance are alerts queued and what happens when their definition is updated?

Thank you

**Comment by kgowdru** [comment]
It takes 15 min. to schedule the alert once it is created.

**Comment by sgarg7** [comment]
Thank you for the response. Is that controlled by the `service.property.scheduling.schedulingRefeshInterval` property?

**Comment by dilipdevaraj-sfdc** [comment]
Yes it is controlled by that property. It is configurable.
service.property.scheduling.schedulingRefeshInterval=300000

This is so that we don't need to hit database every minute but once every 15 minutes.
